from pathlib import Path
import re

path = Path('rl3/eval/rollout.py')
text = path.read_text(encoding='utf-8')
old = "    done = False\n\n    while not done:\n        if is_recurrent:\n            action, lstm_states = model.predict(\n                obs,\n                state=lstm_states,\n                episode_start=episode_starts,\n                deterministic=deterministic,\n            )\n        else:\n            action, _ = model.predict(obs, deterministic=deterministic)\n\n        step_out = env.step(action)\n        if len(step_out) == 5:\n            obs, reward, terminated, truncated, infos = step_out\n            done = bool(terminated or truncated)\n            episode_starts = np.array([done], dtype=bool)\n        else:\n            obs, reward, done, infos = step_out\n            if is_recurrent:\n                episode_starts = np.array([done], dtype=bool)\n\n        info = infos[0] if infos else {}\n        pnl_ret = float(info.get(\"pnl_ret\", 0.0))\n        cost_rate = float(info.get(\"cost_rate\", 0.0))\n        returns.append(pnl_ret - cost_rate)\n        equity.append(float(info.get(\"nav\", 0.0)))\n        weight_vec = info.get(\"weights\")\n        if weight_vec is not None:\n            weights.append([float(x) for x in weight_vec])\n"
if old not in text:
    raise SystemExit('loop block not found for second patch')
new = "    done = False\n\n    while not done:\n        if is_recurrent:\n            action, lstm_states = model.predict(\n                obs,\n                state=lstm_states,\n                episode_start=episode_starts,\n                deterministic=deterministic,\n            )\n        else:\n            action, _ = model.predict(obs, deterministic=deterministic)\n\n        step_out = env.step(action)\n        if len(step_out) == 5:\n            obs, reward, terminated, truncated, info_payload = step_out\n            done = bool(np.asarray(terminated).item() or np.asarray(truncated).item())\n            episode_starts = np.array([done], dtype=bool) if is_recurrent else episode_starts\n        else:\n            obs, reward, done, info_payload = step_out\n            done = bool(np.asarray(done).item())\n            if is_recurrent:\n                episode_starts = np.array([done], dtype=bool)\n\n        info = info_payload[0] if isinstance(info_payload, (list, tuple)) else info_payload or {}\n        reward_val = float(np.asarray(reward).item()) if np.asarray(reward).size else float(reward)
        pnl_ret = float(info.get(\"pnl_ret\", reward_val))\n        cost_rate = float(info.get(\"cost_rate\", 0.0))\n        returns.append(pnl_ret - cost_rate)\n        equity.append(float(info.get(\"nav\", 0.0)))\n        weight_vec = info.get(\"weights\")\n        if weight_vec is not None:\n            weights.append([float(x) for x in weight_vec])\n"
text = text.replace(old, new, 1)
path.write_text(text, encoding='utf-8')
