# 分層監控系統配置
# Tiered Monitoring System Configuration

# 系統配置
system:
  database_path: "data/market_data.db"
  log_level: "INFO"
  max_workers: 10
  request_delay: 0.1

# 三層監控配置
tiers:
  S_tier:
    name: "S級 - 實時監控"
    max_symbols: 40
    update_interval: 1  # 秒
    priority: 100
    description: "持倉股票和熱門股票實時監控"
    
  A_tier:
    name: "A級 - 高頻監控"
    max_symbols: 100
    update_interval: 60  # 秒 (1分鐘)
    priority: 50
    description: "觀察清單股票高頻監控"
    
  B_tier:
    name: "B級 - 全市場掃描"
    max_symbols: 5000
    update_interval: 300  # 秒 (5分鐘)
    priority: 10
    description: "全市場股票定期掃描"

# 信號檢測配置
signals:
  price_breakout:
    enabled: true
    lookback_periods: 20
    breakout_threshold: 0.02  # 2%突破
    volume_confirmation: true
    
  volume_anomaly:
    enabled: true
    volume_multiplier: 2.5  # 平均成交量的2.5倍
    lookback_periods: 20
    
  rsi_signals:
    enabled: true
    overbought_threshold: 70
    oversold_threshold: 30
    period: 14
    
  macd_signals:
    enabled: true
    fast_period: 12
    slow_period: 26
    signal_period: 9
    
  bollinger_bands:
    enabled: true
    period: 20
    std_dev: 2.0

# 層級調整規則
tier_adjustment:
  # 升級規則
  promotion_rules:
    - name: "強信號升級"
      from_tier: "B_tier"
      to_tier: "A_tier"
      conditions:
        signal_strength: 0.8
        min_signals: 2
        time_window: 300  # 5分鐘內
        
    - name: "極強信號升級"
      from_tier: "A_tier"
      to_tier: "S_tier"
      conditions:
        signal_strength: 0.9
        min_signals: 3
        time_window: 180  # 3分鐘內
        
  # 降級規則
  demotion_rules:
    - name: "長期無活動降級"
      from_tier: "S_tier"
      to_tier: "A_tier"
      conditions:
        inactive_duration: 3600  # 1小時無信號
        max_signal_strength: 0.3
        
    - name: "無信號降級"
      from_tier: "A_tier"
      to_tier: "B_tier"
      conditions:
        inactive_duration: 7200  # 2小時無信號
        max_signal_strength: 0.2

# 信號權重配置
signal_weights:
  price_breakout: 0.3
  volume_anomaly: 0.25
  rsi_signals: 0.15
  macd_signals: 0.15
  bollinger_bands: 0.15

# 警報配置
alerts:
  price_change:
    threshold_percent: 5.0
    notification: true
    
  volume_spike:
    threshold_multiplier: 3.0
    notification: true
    
  technical_signals:
    min_signal_strength: 0.7
    notification: true
    
  tier_changes:
    notify_promotions: true
    notify_demotions: false

# 性能優化配置
performance:
  cache_duration: 60  # 秒
  batch_size: 50
  max_concurrent_requests: 20
  retry_attempts: 3
  timeout: 10  # 秒

# 預設股票清單
default_stocks:
  S_tier_seeds:
    - "AAPL"
    - "MSFT"
    - "GOOGL"
    - "AMZN"
    - "TSLA"
    - "META"
    - "NVDA"
    - "BRK-B"
    - "UNH"
    - "JNJ"
    
  A_tier_seeds:
    - "V"
    - "PG"
    - "JPM"
    - "HD"
    - "CVX"
    - "MA"
    - "PFE"
    - "ABBV"
    - "BAC"
    - "KO"
    - "AVGO"
    - "PEP"
    - "TMO"
    - "COST"
    - "WMT"
    - "DIS"
    - "DHR"
    - "ABT"
    - "VZ"
    - "ADBE"

# 健康檢查配置
health_check:
  enabled: true
  interval: 300  # 5分鐘
  max_failure_rate: 0.1  # 10%
  alert_threshold: 0.2  # 20%失敗率時警報